name = "email-provider-links-demo"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# Static assets configuration for Workers
[assets]
directory = "./public"
binding = "ASSETS"
