name = "email-provider-links-demo"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
logpush = true

[vars]
NODE_ENV = "production"

# Build configuration
[build]
command = "npm run build"

# Static assets configuration for Workers
[assets]
directory = "./public"
binding = "ASSETS"
